services:
  # Redis Cache Service - Internal Container (defined first since backend references it)
  - type: redis
    name: realtime-order-management-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow access from all Render services

  # Backend API Service
  - type: web
    name: realtime-order-management-backend
    runtime: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # External MongoDB connection - set in Render dashboard
      - key: MONGODB_URI
        sync: false  # Set manually in Render dashboard
      # Internal Redis connection - from Redis container
      - key: REDIS_URL
        fromService:
          type: redis
          name: realtime-order-management-redis
          property: connectionString
      # Security keys - these will be auto-generated by Render
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: API_KEY_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      # CORS will be set to frontend URL
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: realtime-order-management-frontend
          property: url
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: LOG_LEVEL
        value: info

  # Frontend React App
  - type: web
    name: realtime-order-management-frontend
    runtime: docker
    plan: starter
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: realtime-order-management-backend
          property: url
      - key: VITE_WS_URL
        fromService:
          type: web
          name: realtime-order-management-backend
          property: url
      - key: VITE_APP_NAME
        value: Real-time Order Management System
      - key: VITE_APP_VERSION
        value: 1.0.0
      - key: NODE_ENV
        value: production

# Note: MongoDB is external, Redis is managed by Render
# Configure MongoDB connection in the Render dashboard
